=== semsotsemm/KAR_1SEM/laba_12/Lab12.3.xsd
<?xml version="1.0" encoding="UTF-8"?>
<xs:schema xmlns:xs="http://www.w3.org/2001/XMLSchema">
  <xs:element name="books">
    <xs:complexType>
      <xs:sequence>
        <xs:element name="heading" type="xs:string"/>
        <xs:element name="card" type="xs:string">
          <xs:complexType>
            <xs:sequence>
              <xs:element name="bookfirst" type="xs:string"/>
             <xs:element name="booksecond" type="xs:string"/>
             <xs:element name="bookthird" type="xs:string"/>
              <xs:element name="bookfourth" type="xs:string"/>
              <xs:element name="bookfifth" type="xs:string"/>
              <xs:element name="title" type="xs:string"/>
              <xs:element name="ios" type="xs:string"/>
              <xs:element name="camera" type="xs:string"/>
              <xs:element name="year" type="xs:string"/>
              <xs:element name="price" type="xs:string"/>
            </xs:sequence>
          </xs:complexType>
        </xs:element>
      </xs:sequence>
    </xs:complexType>
  </xs:element>
</xs:schema>

=== semsotsemm/KAR_1SEM/laba_12/Lab12.xml
<?xml version="1.0" encoding="UTF-8"?>
<?xml-stylesheet type="text/css" href="style.css"?>
	<books xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance" xsi:noNamespaceSchemaLocation="Lab12.3.xsd"> 
	<heading> Модели iPhone</heading> 
	<card>
	<bookfirst> 
		<title>Название: iPhone 15</title> 
		<price>Цена: 3500р</price> 
        <ios>iOS: 17 </ios>
        <camera>Камера: 48 Мп </camera>
        <year>Год выпуска: 2023 </year>
	</bookfirst> 
	<booksecond> 
		<title>Название: iPhone 12</title> 
		<price>Цена: 2000р</price> 
        <ios>iOS: 14 </ios>
        <camera>Камера: 12 Мп </camera>
        <year>Год выпуска: 2020 </year>
	</booksecond> 
	<bookthird> 
		<title>Название: iPhone 13</title> 
		<price>Цена: 2700р</price> 
        <ios>iOS: 15 </ios>
        <camera>Камера: 12 Мп </camera>
        <year>Год выпуска: 2021 </year>
	</bookthird> 
	<bookfourth> 
		<title>Название: iPhone 16</title> 
		<price>Цена: 9000р</price> 
        <ios>iOS: 18 </ios>
        <camera>Камера: 48 Мп </camera>
        <year>Год выпуска: 2024 </year>
	</bookfourth> 
	<bookfifth> 
		<title>Название: iPhone 11</title> 
		<price>Цена: 1800р</price> 
        <ios>iOS: 13 </ios>
        <camera>Камера: 12 Мп </camera>
        <year>Год выпуска: 2019 </year>
	</bookfifth> 
	</card>
	</books>
